# Generated by Django 2.2.24 on 2021-10-25 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211025_0932'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
