# Generated by Django 2.2.24 on 2021-10-25 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
