# Generated by Django 2.2.24 on 2021-10-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='admin',
            field=models.BooleanField(default='False'),
        ),
    ]
