# Generated by Django 2.2.24 on 2021-10-25 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211025_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Windows',
            fields=[
                ('id_windows', models.IntegerField(primary_key=True, serialize=False)),
                ('accept', models.BooleanField(default=True)),
                ('receive', models.BooleanField(default=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Users')),
            ],
        ),
    ]
