# Generated by Django 2.2.24 on 2021-10-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_tickets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tickets',
        ),
        migrations.DeleteModel(
            name='Windows',
        ),
    ]
