# Generated by Django 2.2.24 on 2021-10-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_tickets_windows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windows',
            name='id_user',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
