# Generated by Django 2.2.24 on 2021-10-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211026_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='time_close',
            field=models.DateField(null=True),
        ),
    ]
