# Generated by Django 2.2.24 on 2021-10-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20211026_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='id_ticket',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Талона'),
        ),
        migrations.AlterField(
            model_name='windows',
            name='id_window',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Окна'),
        ),
    ]
