# Generated by Django 2.2.24 on 2021-10-27 09:07

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20211026_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogWindows',
            fields=[
                ('id_log', models.IntegerField(primary_key=True, serialize=False)),
                ('id_window', models.IntegerField(verbose_name='ID Окна')),
                ('id', models.IntegerField(null=True, verbose_name=django.contrib.auth.models.User)),
                ('time_login', models.DateField(null=True)),
                ('time_logout', models.DateField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='windows',
            name='id_user',
        ),
        migrations.AddField(
            model_name='tickets',
            name='time_call',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='windows',
            name='id',
            field=models.IntegerField(null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
