# Generated by Django 2.2.24 on 2021-10-27 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20211027_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logwindows',
            name='id',
        ),
        migrations.AddField(
            model_name='logwindows',
            name='operator',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='windows',
            name='id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
