# Generated by Django 2.2.24 on 2021-10-27 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20211027_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windows',
            name='id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
