# Generated by Django 2.2.24 on 2021-10-27 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20211027_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='windows',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='logwindows',
            name='id_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Windows'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='id_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Windows'),
        ),
    ]
