# Generated by Django 2.2.24 on 2021-10-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20211027_1339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogWindows',
        ),
    ]
