# Generated by Django 2.2.24 on 2021-10-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_logwindows'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogWindows',
        ),
    ]
