# Generated by Django 2.2.24 on 2021-10-27 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_delete_logwindows'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogWindows',
            fields=[
                ('id_log', models.IntegerField(primary_key=True, serialize=False)),
                ('operator', models.CharField(max_length=50, null=True)),
                ('time_login', models.DateTimeField(auto_now_add=True)),
                ('time_logout', models.DateTimeField(null=True)),
                ('id_window', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Windows')),
            ],
        ),
    ]
