# Generated by Django 2.2.24 on 2021-10-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20211027_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='time_pause',
            field=models.DurationField(null=True),
        ),
    ]
