# Generated by Django 2.2.24 on 2021-10-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_tickets_time_pause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='time_pause',
            field=models.DurationField(default='0'),
        ),
    ]
