# Generated by Django 2.2.24 on 2021-10-30 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20211030_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='time_pause',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
