# Generated by Django 2.2.24 on 2021-11-06 09:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20211030_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='id_window',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Windows', verbose_name='ID Окна'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='name_ticket',
            field=models.CharField(max_length=50, verbose_name='Талон'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='time_call',
            field=models.DateTimeField(null=True, verbose_name='Время вызова'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='time_close',
            field=models.DateTimeField(null=True, verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='time_pause',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Время пауз'),
        ),
    ]
