# Generated by Django 2.2.24 on 2021-11-08 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20211106_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='id_window',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Windows', verbose_name='Окно'),
        ),
    ]
