# Generated by Django 2.2.24 on 2021-11-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20211127_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='windows',
            name='banking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='windows',
            name='business',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='windows',
            name='finance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='windows',
            name='other',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='windows',
            name='purchase',
            field=models.BooleanField(default=True),
        ),
    ]
