# Generated by Django 2.2.24 on 2022-04-21 09:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_windows_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id_services', models.AutoField(primary_key=True, serialize=False, verbose_name='ID набора сервисов')),
                ('services', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
    ]
