# Generated by Django 2.2.24 on 2022-04-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='operator',
            field=models.CharField(max_length=50, null=True, verbose_name='Оператор'),
        ),
    ]
