# Generated by Django 2.2.24 on 2022-04-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_tickets_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='operator',
            field=models.CharField(max_length=200, null=True, verbose_name='Оператор'),
        ),
    ]
